# Generated by Django 4.2 on 2023-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulsit', '0012_project_project_owner_project_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_foto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
